set(SDL2_IMAGE_SEARCH_PATHS
  /usr/local
  /usr
)

find_path(SDL2_IMAGE_INCLUDE_DIR SDL_image.h
  HINTS $ENV{SDL2_IMAGEDIR}
  PATH_SUFFIXES "include/SDL2"
  PATHS ${SDL2_IMAGE_SEARCH_PATHS}
)

find_library(SDL2_IMAGE_LIBRARY_TEMP
  NAMES SDL2_image
  HINTS $ENV{SDL2_IMAGEDIR}
  PATH_SUFFIXES "lib64" "lib"
  PATHS ${SDL2_IMAGE_SEARCH_PATHS}
)

if(SDL2_IMAGE_LIBRARY_TEMP)
  # For MinGW library
  if(MINGW)
    set(SDL2_IMAGE_LIBRARY_TEMP ${MINGW32_LIBRARY} ${SDL2_IMAGE_LIBRARY_TEMP})
  endif(MINGW)

  set(SDL2_IMAGE_LIBRARY ${SDL2_IMAGE_LIBRARY_TEMP} CACHE STRING "Where the SDL2_Image Library can be found")
  set(SDL2_IMAGE_LIBRARY_TEMP "${SDL2_IMAGE_LIBRARY_TEMP}" CACHE INTERNAL "")
endif(SDL2_IMAGE_LIBRARY_TEMP)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(SDL2_IMAGE
  REQUIRED_VARS
  SDL2_IMAGE_LIBRARY
  SDL2_IMAGE_INCLUDE_DIR
)
